name: Continuous Integration

on:
  pull_request:
    branches: [development, main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Step 1: Verifica formato (falla rápido si hay problemas)
      - name: Check code formatting
        run: npm run format:check

      # Step 2: Verifica calidad de código
      - name: Lint code
        run: npm run lint

      # Step 3: Ejecuta tests
      - name: Run tests
        run: npm run test

      # Step 4: Compila el proyecto
      - name: Build project
        run: npm run build

      # Step 5: Validación de Docker (opcional)
      - name: Validate Docker build
        run: docker build -t identity-svc:test .
        if: success()
